// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fishercpp
NumericMatrix fishercpp(NumericMatrix& Xcpp, NumericVector& mucpp);
RcppExport SEXP penMSM_fishercpp(SEXP XcppSEXP, SEXP mucppSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix& >::type Xcpp(XcppSEXP );
        Rcpp::traits::input_parameter< NumericVector& >::type mucpp(mucppSEXP );
        NumericMatrix __result = fishercpp(Xcpp, mucpp);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
